my-blog:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.8.128
    port: 3306
    database: my_blog
    username: root
    password: "2861587619"
  redis:
    host: localhost
    port: 6379
    password: 2861587619
    database: 0